### List all messages
GET http://localhost:3000/messages

### Create a new messsage
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "message1"
}

### Get particular message
GET http://localhost:3000/messages/1